spring:
  application:
    name: demo
  profiles:
    active: "@profiles.active@"
  config:
    import: 
      - classpath:application-${spring.application.name}.yml
      - classpath:application-${spring.application.name}-${spring.profiles.active}.yml
info:
  name: ${spring.application.name}
  desc: "@project.description@"
  version: "@project.version@"
  ip: ${spring.cloud.client.ip-address}:${server.port}
application:
  log:
    level: "@profiles.log.level@"
    path: "@profiles.log.path@"