spring:
  http:
    encoding:
      charset: utf-8
      enabled: true
      force: true
  servlet:
    multipart:
      max-file-size: 10KB
      max-request-size: 100KB
server:
  tomcat:
    uri-encoding: utf-8
javaeaseframe:
  interceptor:
    login:
      enable: false
      uncheckUrl: /error,/refresh,/health,/doc.html,/swagger-resources,/v2/api-docs,/favicon.ico,/webjars/*,/inner/*
    auth:
      enable: false
      uncheckUrl: /error,/refresh,/health,/common/login,/api/*
    log:
      printPosition: 
        beforeAdvice:
          enable: false
        afterAdvice:
          enable: true
          fetchFromNativeRequestEnable: true
          printRequestUser: false
          printRequestBody: true
          printResponseBody: true
          format: statMOD=${MOD} statPV=${PV} statIP=${IP} statURL=${URL} statDuration=${Duration} ${Message}
  web:
    cors:
      enable: true
    cacheBody:
      enable: true
      UrlPatterns: 
        - /open/*
        - /inner/*
        - /v2/*
    resourceHandlers:
      "[/webjars/**]": "/webjars/"
      "[/*.html]": "/"
  mybatis:
    root-path: com.gm
    type-aliases-package: com.gm.**.model
    mapper-locations: classpath*:sqlmap/**/*.xml
  transaction:
    enable: true
    pointcut: 
      - "* com.gm..*Service.*(..)"
    methods:
      - name: "save*"
        propagation: "REQUIRED"
      - name: "update*"
        propagation: "REQUIRED"
      - name: "remove*"
        propagation: "REQUIRED"
      - name: "*NewTx"
        propagation: "REQUIRES_NEW"
      - name: "*NonTx"
        propagation: "NOT_SUPPORTED"
      - name: "*"
        propagation: "SUPPORTS"
        readOnly: true
  knife4j:
    enable: true
    basic:
      enable: false
      username: admin
      password: 123456
    openapi:
      title: JavaEaseFrame框架-demo项目
      description: "这是应用的描述信息"
      email: guomin@javaeaseframe.com
      concat: guomin
      group:
        group1:
          group-name: 分组1
          api-rule: package
          api-rule-resources:
            - com.gm.javaeaseframe.demo.weather.web
  xxljob:
    enable: false
    adminAddresses: http://127.0.0.1:8080/xxl-job-admin
    appname: ${spring.application.name}