server:
  port: 17300
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/javaeaseframe-demo?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: "123456"
    druid:
      initialSize: 1
      minIdle: 1
      maxActive: 3
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      filters: stat
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      web-stat-filter:
        enabled: false
      stat-view-servlet:
        enabled: false
